
#ADD_DEFINITIONS(-DdSINGLE)
#ADD_DEFINITIONS(-DdTRIMESH_ENABLE)
#ADD_DEFINITIONS(-DODE_LIB)

ADD_DEFINITIONS("-D_CRT_SECURE_NO_DEPRECATE=1")
ADD_DEFINITIONS("-D_CRT_SECURE_NO_WARNINGS=1")
ADD_DEFINITIONS("-D_SCL_SECURE_NO_DEPRECATE=1")
ADD_DEFINITIONS("-D_CRT_NONSTDC_NO_DEPRECATE=1")

ADD_DEFINITIONS("-D__TBB_NO_IMPLICIT_LINKAGE=1")
ADD_DEFINITIONS("-DTBB_NO_LEGACY=1")

ADD_DEFINITIONS("-DDIRECTINPUT_VERSION=0x800")
ADD_DEFINITIONS("-DFT_CONFIG_OPTION_SYSTEM_ZLIB=1")

IF(CMAKE_BUILD_TYPE STREQUAL "Debug")
	ADD_DEFINITIONS("-D_DEBUG")
	ADD_DEFINITIONS("-DTBB_DO_ASSERT")
ELSE(CMAKE_BUILD_TYPE STREQUAL "Debug")
	ADD_DEFINITIONS("-D_SECURE_SCL=0")
	ADD_DEFINITIONS("-D_HAS_ITERATOR_DEBUGGING=0")
	ADD_DEFINITIONS("-DNDEBUG")
ENDIF(CMAKE_BUILD_TYPE STREQUAL "Debug")
